/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/endpoints/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search runnable endpoints
         * @description Searches the data sources by keyword and returns ranked endpoint summaries, each identified by provider, endpoint, and endpoint_version, with its price and run mode. Several providers may sell the same capability; the ranking is relevance-only and the price is shown alongside so the caller chooses. Pages are short by default (5, up to 20): read `total` for how many candidates exist, then pass next_cursor back as cursor for the next page; the cursor is bound to the query. The list is already scoped to the calling key's effective policy: every endpoint in it is one this key can run. Each hit carries a `score`, the cosine similarity between the query and that endpoint's description: use it to compare rows, and inspect an endpoint before running it. The ranking returns its nearest candidates rather than withholding them, so neither a page of low scores nor reaching the last page shows that a capability is absent — try other words before concluding that.
         */
        post: operations["endpoints-search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/endpoints/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inspect one endpoint: schemas, price, version
         * @description Returns the full execution contract of one endpoint: the provider-native input JSON Schema, the output JSON Schema when a trustworthy one exists (null otherwise — samples never imply a contract), its source, the price with every charge clause, the current endpoint_version, the run mode, a sample input, and a link to the provider's own documentation. A sync endpoint also publishes timeout_ms, the maximum time from request to terminal response — set your HTTP client timeout above it. Passing endpoint_version selects a supported version, including an older one. Compatible updates keep that version. Unavailable or retired versions answer 409. Price can change without a version change; new Runs use the Price at admission, while accepted Runs keep their original Price.
         */
        post: operations["endpoints-inspect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs
         * @description Lists runs in reverse order of creation time, with optional filters on status, provider, and endpoint. This endpoint uses cursor pagination. The list is scoped by the effective policy: runs of an endpoint this key cannot run are not readable either.
         */
        get: operations["runs-list"];
        put?: never;
        /**
         * Run an endpoint
         * @description Admits one execution at the selected supported Endpoint version (the default if omitted). The version does not lock Price: new Runs use its current Price, and accepted Runs keep that exact Price through settlement. The policy is checked, a hold is reserved for the price's maximum charge, and a run is created. Input is provider-native — construct it against the inspected input_schema. A sync endpoint always answers 200 with the terminal run inside its published timeout_ms — it never returns 202, so no polling code is needed. An async endpoint answers 200 when the run is terminal within a short server budget, otherwise 202 with the in-flight run, which you can poll or stop. Status reports whether a usable provider response won settlement, never whether the provider accepted the request: a provider 404 or 500 is a COMPLETED run whose provider_response carries the received status, charged by the price's NO_RESULT or PROVIDER_ERROR clause. The Idempotency-Key header is required — a retry with the same key returns the same run and is never charged twice, while the same key with a different request body returns 409. Balance and policy refusals happen before admission and create no run.
         */
        post: operations["runs-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get run status and output
         * @description Returns the current state of one run. When the status is COMPLETED, provider_response is not null: a 2xx body is in output (any JSON shape, null for an empty body), and a non-2xx body is in provider_response.error. When the status is FAILED, failure is not null. Status does not imply that money moved: charge_usd and charge_basis are reported independently, and a FAILED run with a non-zero charge is a normal outcome, not a contradiction.
         */
        get: operations["runs-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop a run
         * @description Requests a stop. Dispatch wins the race: if no provider call has been journaled yet, the run becomes STOPPED immediately, its hold is closed, and the charge is 0. If a call has already been journaled, only stop_requested_at is recorded and the run continues to COMPLETED or FAILED — a result that was paid for is never discarded. A run that is already in a terminal status returns 409, because for billing purposes "I stopped it" and "it had already finished" are not equivalent and the request must not succeed silently.
         */
        post: operations["runs-stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get balance, held and available
         * @description Returns the balance triple: balance (settled funds), held (reservations for in-flight runs), and available (balance minus held — the number a new run is admitted against). This is also the cheapest authentication probe.
         */
        get: operations["balance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/balance/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every balance movement
         * @description Lists every balance movement in reverse time order: charge, refund, topup, grant, and adjustment. Amounts are exact USD decimal strings, signed (a charge is negative): summing them with decimal arithmetic — not floats — reconciles the balance, and each entry carries balance_after_usd. This endpoint uses cursor pagination.
         */
        get: operations["balance-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ValidationFailedEncoded: {
            error: {
                /** @enum {string} */
                code: "validation_failed";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        RateLimitedEncoded: {
            error: {
                /** @enum {string} */
                code: "rate_limited";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        UnauthorizedEncoded: {
            error: {
                /** @enum {string} */
                code: "unauthorized";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        NotFoundEncoded: {
            error: {
                /** @enum {string} */
                code: "not_found";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        EndpointVersionMismatchEncoded: {
            error: {
                /** @enum {string} */
                code: "endpoint_version_mismatch";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        IdempotencyKeyRequiredEncoded: {
            error: {
                /** @enum {string} */
                code: "idempotency_key_required";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        IdempotencyConflictEncoded: {
            error: {
                /** @enum {string} */
                code: "idempotency_conflict";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        EndpointNotPermittedEncoded: {
            error: {
                /** @enum {string} */
                code: "endpoint_not_permitted";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        InsufficientBalanceEncoded: {
            error: {
                /** @enum {string} */
                code: "insufficient_balance";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        ServiceUnavailableEncoded: {
            error: {
                /** @enum {string} */
                code: "service_unavailable";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
        ConflictEncoded: {
            error: {
                /** @enum {string} */
                code: "conflict";
                message: string;
                reason?: string | null;
                control?: string | null;
                retry_after_ms?: (number | null) | null;
                details?: Record<string, never> | null;
            };
            request_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "endpoints-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query?: string | null;
                    limit?: number | null;
                    cursor?: string | null;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            provider: string;
                            /** @description The Provider's brand name, for display: "People Data Labs" for provider "pdl". Identity stays with `provider` — that is the value run and inspect take, and this one is never sent back. */
                            provider_label: string;
                            endpoint: string;
                            endpoint_version: number;
                            name: string;
                            description: string;
                            tags: string[];
                            price: {
                                rule: {
                                    /** @enum {string} */
                                    type: "flat";
                                    /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                    amount_usd: string;
                                } | {
                                    /** @enum {string} */
                                    type: "per_result";
                                    /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                    per_result_usd: string;
                                    /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                    cap_usd: string;
                                    /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                    partial_usd?: string;
                                };
                                charges: {
                                    /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                    NO_RESULT: string;
                                    /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                    PROVIDER_ERROR: string;
                                    /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                    TIMED_OUT: string;
                                    /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                    INTERNAL: string;
                                };
                            };
                            /** @enum {string} */
                            run_mode: "sync" | "async";
                            timeout_ms?: number | null;
                            /** @description Cosine similarity between the query and this endpoint's searchable text, in [-1, 1]; null when semantic scoring did not run. A similarity signal for comparing rows, not a verdict: ranking fuses two arms, and neither a low score nor the end of the results shows that a capability is absent. */
                            score: (number | ("Infinity" | "-Infinity" | "NaN")) | null;
                        }[];
                        next_cursor: string | null;
                        /** @description Total number of ranked candidates across all pages. */
                        total: number;
                    };
                };
            };
            /** @description ValidationFailed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationFailedEncoded"] | components["schemas"]["ValidationFailedEncoded"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedEncoded"];
                };
            };
            /** @description RateLimited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedEncoded"];
                };
            };
        };
    };
    "endpoints-inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    provider: string;
                    endpoint: string;
                    endpoint_version?: number | null;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        provider: string;
                        /** @description The Provider's brand name, for display: "People Data Labs" for provider "pdl". Identity stays with `provider` — that is the value run and inspect take, and this one is never sent back. */
                        provider_label: string;
                        endpoint: string;
                        endpoint_version: number;
                        name: string;
                        description: string;
                        tags: string[];
                        price: {
                            rule: {
                                /** @enum {string} */
                                type: "flat";
                                /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                amount_usd: string;
                            } | {
                                /** @enum {string} */
                                type: "per_result";
                                /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                per_result_usd: string;
                                /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                cap_usd: string;
                                /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                partial_usd?: string;
                            };
                            charges: {
                                /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                NO_RESULT: string;
                                /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                PROVIDER_ERROR: string;
                                /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                TIMED_OUT: string;
                                /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                                INTERNAL: string;
                            };
                        };
                        /** @enum {string} */
                        run_mode: "sync" | "async";
                        timeout_ms?: number | null;
                        /** @enum {string} */
                        method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD";
                        input_schema: Record<string, never>;
                        output_schema: Record<string, never> | null;
                        output_schema_source: ("provider" | "glasser") | null;
                        sample_input: Record<string, never>;
                        doc_url: string | null;
                    };
                };
            };
            /** @description ValidationFailed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationFailedEncoded"] | components["schemas"]["ValidationFailedEncoded"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedEncoded"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundEncoded"];
                };
            };
            /** @description EndpointVersionMismatch */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointVersionMismatchEncoded"];
                };
            };
            /** @description RateLimited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedEncoded"];
                };
            };
        };
    };
    "runs-list": {
        parameters: {
            query?: {
                limit?: string;
                cursor?: string | null;
                status?: ("QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "STOPPED") | null;
                provider?: string | null;
                endpoint?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            run_url: string;
                            provider: string;
                            endpoint: string;
                            endpoint_version: number;
                            /** @enum {string} */
                            status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "STOPPED";
                            failure: {
                                /** @enum {string} */
                                kind: "TIMED_OUT" | "INTERNAL";
                                message: string;
                            } | null;
                            input: Record<string, never>;
                            output: unknown;
                            provider_response: {
                                http_status: number;
                                error?: unknown | null;
                            } | null;
                            charge_usd: string | null;
                            charge_basis: {
                                /** @enum {string} */
                                clause: "rule" | "NO_RESULT" | "PROVIDER_ERROR" | "TIMED_OUT" | "INTERNAL";
                                quantity: number | null;
                            } | null;
                            stoppable: boolean;
                            stop_requested_at: string | null;
                            /**
                             * Format: date-time
                             * @description ISO-8601 UTC timestamp
                             */
                            created_at: string;
                            started_at: string | null;
                            completed_at: string | null;
                        }[];
                        next_cursor: string | null;
                    };
                };
            };
            /** @description ValidationFailed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationFailedEncoded"] | components["schemas"]["ValidationFailedEncoded"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedEncoded"];
                };
            };
            /** @description RateLimited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedEncoded"];
                };
            };
        };
    };
    "runs-create": {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    provider: string;
                    endpoint: string;
                    input?: Record<string, never>;
                    endpoint_version?: number | null;
                };
            };
        };
        responses: {
            /** @description a terminal run: COMPLETED, FAILED or STOPPED */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        run_url: string;
                        provider: string;
                        endpoint: string;
                        endpoint_version: number;
                        /** @enum {string} */
                        status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "STOPPED";
                        failure: {
                            /** @enum {string} */
                            kind: "TIMED_OUT" | "INTERNAL";
                            message: string;
                        } | null;
                        input: Record<string, never>;
                        output: unknown;
                        provider_response: {
                            http_status: number;
                            error?: unknown | null;
                        } | null;
                        charge_usd: string | null;
                        charge_basis: {
                            /** @enum {string} */
                            clause: "rule" | "NO_RESULT" | "PROVIDER_ERROR" | "TIMED_OUT" | "INTERNAL";
                            quantity: number | null;
                        } | null;
                        stoppable: boolean;
                        stop_requested_at: string | null;
                        /**
                         * Format: date-time
                         * @description ISO-8601 UTC timestamp
                         */
                        created_at: string;
                        started_at: string | null;
                        completed_at: string | null;
                    };
                };
            };
            /** @description an in-flight run: QUEUED or RUNNING */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        run_url: string;
                        provider: string;
                        endpoint: string;
                        endpoint_version: number;
                        /** @enum {string} */
                        status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "STOPPED";
                        failure: {
                            /** @enum {string} */
                            kind: "TIMED_OUT" | "INTERNAL";
                            message: string;
                        } | null;
                        input: Record<string, never>;
                        output: unknown;
                        provider_response: {
                            http_status: number;
                            error?: unknown | null;
                        } | null;
                        charge_usd: string | null;
                        charge_basis: {
                            /** @enum {string} */
                            clause: "rule" | "NO_RESULT" | "PROVIDER_ERROR" | "TIMED_OUT" | "INTERNAL";
                            quantity: number | null;
                        } | null;
                        stoppable: boolean;
                        stop_requested_at: string | null;
                        /**
                         * Format: date-time
                         * @description ISO-8601 UTC timestamp
                         */
                        created_at: string;
                        started_at: string | null;
                        completed_at: string | null;
                    };
                };
            };
            /** @description ValidationFailed | IdempotencyKeyRequired */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationFailedEncoded"] | components["schemas"]["IdempotencyKeyRequiredEncoded"] | components["schemas"]["ValidationFailedEncoded"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedEncoded"];
                };
            };
            /** @description InsufficientBalance */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsufficientBalanceEncoded"];
                };
            };
            /** @description EndpointNotPermitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointNotPermittedEncoded"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundEncoded"];
                };
            };
            /** @description IdempotencyConflict | EndpointVersionMismatch */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdempotencyConflictEncoded"] | components["schemas"]["EndpointVersionMismatchEncoded"];
                };
            };
            /** @description RateLimited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedEncoded"];
                };
            };
            /** @description ServiceUnavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceUnavailableEncoded"];
                };
            };
        };
    };
    "runs-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        run_url: string;
                        provider: string;
                        endpoint: string;
                        endpoint_version: number;
                        /** @enum {string} */
                        status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "STOPPED";
                        failure: {
                            /** @enum {string} */
                            kind: "TIMED_OUT" | "INTERNAL";
                            message: string;
                        } | null;
                        input: Record<string, never>;
                        output: unknown;
                        provider_response: {
                            http_status: number;
                            error?: unknown | null;
                        } | null;
                        charge_usd: string | null;
                        charge_basis: {
                            /** @enum {string} */
                            clause: "rule" | "NO_RESULT" | "PROVIDER_ERROR" | "TIMED_OUT" | "INTERNAL";
                            quantity: number | null;
                        } | null;
                        stoppable: boolean;
                        stop_requested_at: string | null;
                        /**
                         * Format: date-time
                         * @description ISO-8601 UTC timestamp
                         */
                        created_at: string;
                        started_at: string | null;
                        completed_at: string | null;
                    };
                };
            };
            /** @description ValidationFailed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationFailedEncoded"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedEncoded"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundEncoded"];
                };
            };
            /** @description RateLimited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedEncoded"];
                };
            };
        };
    };
    "runs-stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        run_url: string;
                        provider: string;
                        endpoint: string;
                        endpoint_version: number;
                        /** @enum {string} */
                        status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED" | "STOPPED";
                        failure: {
                            /** @enum {string} */
                            kind: "TIMED_OUT" | "INTERNAL";
                            message: string;
                        } | null;
                        input: Record<string, never>;
                        output: unknown;
                        provider_response: {
                            http_status: number;
                            error?: unknown | null;
                        } | null;
                        charge_usd: string | null;
                        charge_basis: {
                            /** @enum {string} */
                            clause: "rule" | "NO_RESULT" | "PROVIDER_ERROR" | "TIMED_OUT" | "INTERNAL";
                            quantity: number | null;
                        } | null;
                        stoppable: boolean;
                        stop_requested_at: string | null;
                        /**
                         * Format: date-time
                         * @description ISO-8601 UTC timestamp
                         */
                        created_at: string;
                        started_at: string | null;
                        completed_at: string | null;
                    };
                };
            };
            /** @description ValidationFailed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationFailedEncoded"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedEncoded"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundEncoded"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictEncoded"];
                };
            };
            /** @description RateLimited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedEncoded"];
                };
            };
        };
    };
    balance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                        balance_usd: string;
                        /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                        held_usd: string;
                        /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                        available_usd: string;
                    };
                };
            };
            /** @description ValidationFailed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationFailedEncoded"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedEncoded"];
                };
            };
            /** @description RateLimited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedEncoded"];
                };
            };
        };
    };
    "balance-history": {
        parameters: {
            query?: {
                limit?: string;
                cursor?: string | null;
                kind?: ("charge" | "refund" | "topup" | "grant" | "adjustment") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            /** @enum {string} */
                            kind: "charge" | "refund" | "topup" | "grant" | "adjustment";
                            amount_usd: string;
                            /** @description Exact USD decimal string (min 2, max 6 decimals, one canonical spelling). Sum with decimal arithmetic or scale by 10^6 — never floats. */
                            balance_after_usd: string;
                            run_id: string | null;
                            description: string;
                            /**
                             * Format: date-time
                             * @description ISO-8601 UTC timestamp
                             */
                            created_at: string;
                        }[];
                        next_cursor: string | null;
                    };
                };
            };
            /** @description ValidationFailed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationFailedEncoded"] | components["schemas"]["ValidationFailedEncoded"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedEncoded"];
                };
            };
            /** @description RateLimited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitedEncoded"];
                };
            };
        };
    };
}
